steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/poc-dbt-service/poc-dbt-image-service-v1',
           '.']
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/poc-dbt-service/poc-dbt-image-service-v1']
options:
  logging: CLOUD_LOGGING_ONLY