poc_dbt:
  outputs:
    dev:
      dataset: dbt_poc_bch
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-account.json
      location: us-east4
      method: service-account
      priority: interactive
      project: proyecto-facu-bch
      threads: 1
      type: bigquery
  target: dev


loa:
  outputs:
    dev:
      dataset: transformation_stage
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-account.json      
      location: us-east4
      method: service-account
      priority: interactive
      project: proyecto-facu-bch
      threads: 3
      type: bigquery
  target: dev